### ISSUE TITLE
Image Max URL is removed from Greasyfork

### ISSUE THREAD

**Issue by Fooftilly** [bvolpato/awesome-userscripts#18]
Image Max URL script is removed from Greasyfork, but the script is still available on Github and Openuserjs. Maybe you can replace the broken link with one of these:
https://github.com/qsniyg/maxurl/blob/master/userscript.user.js
https://github.com/qsniyg/maxurl
https://openuserjs.org/scripts/qsniyg/Image_Max_URL

**Comment by qsniyg** [comment]
Thanks! I forgot to update this.
