### ISSUE TITLE
AntiAdware Link is Broken

### ISSUE THREAD

**Issue by Dawson-Graham** [bvolpato/awesome-userscripts#20]
AntiAdware [link](https://greasyfork.org/en/scripts/4294-antiadware) is broken (404 error). I wasn't able to find a new one.

**Comment by adamlui** [comment]
> AntiAdware [link](https://greasyfork.org/en/scripts/4294-antiadware) is broken (404 error). I wasn't able to find a new one.

Hey @Dawson-Graham I found a working link @ https://github.com/handyuserscripts/antiadware
