### ISSUE TITLE
FYI: some fingerprinting scripts

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [bvolpato/awesome-userscripts#4]
snip

**Comment by bvolpato** [comment]
Nice! A lot of good content :)

Want to open a PR for it, or want me to do it?


Thank you @Thorin-Oakenpants

**Comment by Thorin-Oakenpants** [comment]
I'll let you do it, I'm a bit snowed under, thanks :)

**Comment by Thorin-II** [comment]
this is now obsolete
